### ISSUE TITLE
Issue while running predict-battery-life-with-AML.ipynb notebook in AI Exp 3

### ISSUE THREAD

**Issue by GhumanNavneet** [solliancenet/tech-immersion-data-ai#20]
The following command is not getting completed automatically in the notebook https://github.com/solliancenet/tech-immersion-data-ai/blob/master/lab-files/ai/3/predict-battery-life-with-AML.ipynb : _

> remote_run.wait_for_completion(show_output=True)

But, if we go to AML Studio and check for completion, it is showing as complete. We are able to run other cells

**Comment by shirolkar** [comment]
@GhumanNavneet @PraveenAnil 
This issue is fixed. Please use the latest notebook to confirm: https://github.com/solliancenet/tech-immersion-data-ai/blob/master/lab-files/ai/3/predict-battery-life-with-AML.ipynb
