### ISSUE TITLE
Issue with importing a repository in Azure DevOps in AI Exp 6

### ISSUE THREAD

**Issue by PraveenAnil** [solliancenet/tech-immersion-data-ai#21]
Currently, there is a bug in Azure DevOps while importing a repository to a project.

Here is the workaround  I used for MLOps with Azure Machine Learning and Azure DevOps below :

**Solution :**
Before starting Task 2, 
1. Go to Account settings and Select “Preview Features“

2. Turn off the “New Repos landing pages” preview feature.

**Comment by shirolkar** [comment]
@PraveenAnil This issue is addressed. I have added instructions incase users run into this issue. Thanks.
