### ISSUE TITLE
Monitor the Run Details cell is failing.

### ISSUE THREAD

**Issue by SeeratArora** [solliancenet/tech-immersion-data-ai#27]
**Monitor the Run Details** cell is failing.

![image](https://user-images.githubusercontent.com/50323628/83191997-8640b800-a152-11ea-8254-01464f45d4de.png)

Error: **cannot import name 'joblib'**

![image](https://user-images.githubusercontent.com/50323628/83192019-8fca2000-a152-11ea-8c4f-2eba6c25dad8.png)

Can you please look into this?

Thanks,
Seerat

**Comment by shirolkar** [comment]
@SeeratArora This should be fixed. Please let me know if you still run into issues. Thanks.

**Comment by SeeratArora** [comment]
@shirolkar Thanks a lot! It's working perfectly now.
