### ISSUE TITLE
Databricks Streaming for live end-to-end pipeline throwing error 

### ISSUE THREAD

**Issue by himanshuahlawat31** [solliancenet/tech-immersion-data-ai#28]
When we run all the cells in  Databricks streaming for live end to end pipeline it was throwing error 
![image](https://user-images.githubusercontent.com/57964598/83554922-1c962480-a52b-11ea-945e-61bfc5e1733e.png)

**Comment by kylebunting** [comment]
@himanshuahlawat31, could you verify for me that the data feed was still running at the time you attempted to run these cells? If the data generator has stopped running, it will need to be restarted for these cells to work correctly, as that is where the streaming data is created.

**Comment by himanshuahlawat31** [comment]
@kylebunting , yes the data feed was still running when i attempted to run these cells

**Comment by himanshuahlawat31** [comment]
Yes this is related to Data -Exp6 , Task 3
