### ISSUE TITLE
Task 3 Step 7: name parameter is brittle, error unhelpful

### ISSUE THREAD

**Issue by jpwarren** [solliancenet/tech-immersion-data-ai#3]
In step 7 of task 3, the `deploy_bot.ps1` script takes parameters. The `name` parameter is not a free-text string and you have to get this exactly right.

While the instructions say the `name` should be of the form `tech-immersion-<YOUR_UNIQUE_IDENTIFIER>` the example in the image is of the form `tech-immersion-bot-<IDENTIFIER>` or at least it appears to be.

If you name the thing something like `tech-immersion-bot-9000` the script fails at the
`az group create -g …` phase with an authorisation error, which doesn't make it clear that the issue is with the value for the `name` parameter.

**Comment by joelhulen** [comment]
Thanks for letting me know. I'll update the documentation to explicitly say to set the name to the exact same name as your resource group. If it's a different name, then it attempts to create a new RG based off that name, which you are not allowed to do within the hosted environment.
