### ISSUE TITLE
Form indexer is showing as failed in Azure portal

### ISSUE THREAD

**Issue by srushti-714** [solliancenet/tech-immersion-data-ai#4]
In Task 9:(Create Forms Recognizer Pipeline) step 4 is working fine i.e  getting a message as successfully trained form recognizer model on console but it is showing as failed in portal(step 5)
Please look after the issue as soon as possible.
Here is the screenshot attached.
![aie2issue](https://user-images.githubusercontent.com/55180169/65952555-bd45b900-e45f-11e9-85fc-026f8eed7077.png)
Thank you.

**Comment by kylebunting** [comment]
@srushti-714, I am unable to reproduce any errors around this, but I believe the problem most likely lies in the `serviceEndpoint` specified for the Forms Recognizer service. This needs to be correctly set in both the `appsettings.json` file for the PipelineEnhancer project and at the top of the `AnalyzeFormFunction.cs` file in the CustomSkillFunctions project. Please verify you have the correct endpoint specified in both locations.

To help clarify the required steps, I pushed a few changes to the steps for Tasks 4 and 9 in commit #be8c947.

Please let me know if you continue to have issues.
