### ISSUE TITLE
Deployment error (task 2, step 6-8)

### ISSUE THREAD

**Issue by marcscho** [solliancenet/tech-immersion-data-ai#8]
Hi

We're following the instructions for the deployment and get the following

C:\lab-files\ai\1\automotiveskill\automotiveskill>pwsh -ExecutionPolicy Bypass -File Deployment\Scripts\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): ti-116901
? Azure resource group region: westus
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): Abc!1234567890
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): 926*******************9f1
Found an existing application instance of "962513b4******************94453872". We will patch it
> Creating resource group ...
> Validating Azure deployment ...
> Deploying Azure services (this could take a while)...
Deployment failed. Correlation ID: ac8a45**************90ee9. {
  "Code": "Unauthorized",
  "Message": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.",
  "Target": null,
  "Details": [
    {
      "Message": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option."
    },
    {
      "Code": "Unauthorized"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "52020",
        "MessageTemplate": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.",
        "Parameters": [
          "default"
        ],
        "Code": "Unauthorized",
        "Message": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option."
      }
    }
  ],
  "Innererror": null
}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\lab-files\ai\1\automotiveskill\automotiveskill\Deployment\Scripts\..\deploy_log.txt
+ To delete this resource group, run 'az group delete -g ti-116901 --no-wait'

C:\lab-files\ai\1\automotiveskill\automotiveskill>

**Comment by joelhulen** [comment]
@marcscho I encountered that same error last week when deploying an App Service from an ARM template to `westus`. The error was related to an issue in the region that affected by Azure subscription and temporarily did not allow me to provision new App Service accounts. Could you please try again in a different region, such as `eastus` or `centralus`?

**Comment by joelhulen** [comment]
@marcscho Could you please let me know if you are still facing this issue?

**Comment by marcscho** [comment]
Thanks @joelhulen; unfortunately I won't be able to test it before Dec. 11th as I don't have the environment available anymore until then. Will post back here afterwards.
